version: '3'

services:

    client:
      container_name: client
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - "3000:3000"
      volumes: 
        - /app/node_modules
        - .:/app

    server:
      container_name: server
      image: server-image
      build: ./data/Dockerfile.dev
        
      ports: 
        - "8000:8000"
      volumes:
        - ./data/db.json:/data/db.json
      command: json-server --watch /data/db.json --host 0.0.0.0 --port 8000